#!/usr/bin/env bash

# thanks for https://gist.github.com/hrules6872/8077d6799ba53499be361b931059eda2#file-pre-commit

PROTECTED_BRANCH='master'
CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ "${PROTECTED_BRANCH}" == "${CURRENT_BRANCH}" ]]; then
  exec </dev/tty
  while true; do
    read -r -p "You're about to commit to master, want some bacon? [y|n]" ANSWER
    case ${ANSWER} in
    [Yy]*) exit 0 ;; # tells git to continue normally
    [Nn]*) exit 1 ;; # tells git to abort operation
    esac
  done
fi

exit 0 # everything is ok
